# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "<a href='/' style='text-decoration:none; color: white'> Andrei's Playground </a>"
author: Andrei Rusu
email: rusu.c.andrei@gmail.com
description: # this means to ignore newlines until "baseurl:"
    Thank you for visiting my playground! <br /><br />

    My name is <a href="/MyCV">Andrei Rusu</a> and I am an enthusiastic PhD student in Artificial Intelligence with good knowledge of computer architecture, 
    passion for machine learning and data analysis, keen interest in revolutionary technologies, and eagerness for new experiences. <br /><br />

    This page is not just a personal blog, it is meant to be a map into my world!
baseurl: "/"
url: "https://andrei-rusu.github.io"
github_username:  andrei-rusu

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
  
kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false
  # parse markdown inside block-level HTML tag
  parse_block_html: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
